// src/components/UI/Modal.jsx
import { X, Copy } from 'lucide-react'

export default function Modal({ title, onClose, content, showToast }) {
  const handleCopy = () => {
    navigator.clipboard?.writeText(content)
    showToast('Copied to clipboard!')
  }

  return (
    <div className="fixed inset-0 bg-ink/70 z-50 flex items-center justify-center p-4 animate-fade-in">
      <div className="bg-white rounded-xl max-w-2xl w-full max-h-[80vh] overflow-y-auto shadow-2xl">
        <div className="sticky top-0 bg-white border-b border-cream3 p-5 flex justify-between items-center">
          <div>
            <h3 className="font-serif text-xl text-ink font-normal">{title}</h3>
            <p className="text-ink3 text-xs mt-1">Generated by AI — feel free to edit and personalize</p>
          </div>
          <button onClick={onClose} className="text-ink3 hover:text-ink transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>
        
        <div className="p-6">
          <div className="text-ink2 text-sm leading-relaxed whitespace-pre-wrap">
            {content}
          </div>
          
          <button
            onClick={handleCopy}
            className="mt-6 w-full bg-gold text-ink py-3 rounded-lg text-sm font-semibold hover:bg-gold2 transition-all flex items-center justify-center gap-2"
          >
            <Copy className="w-4 h-4" />
            Copy to Clipboard
          </button>
        </div>
      </div>
    </div>
  )
}